outfile: com_remove.o inc_file.o macro.o pre.o
	cc com_remove.o inc_file.o macro.o pre.o -o outfile
com_remove.o: com_remove.c
	cc -c com_remove.c
inc_file.o: inc_file.c
	cc -c inc_file.c
macro.o: macro.c
	cc -c macro.c
pre.o: pre.c
	cc -c pre.c
