outfile: add.o main.o delete.o other.o print.o file.o
	cc  add.o main.o delete.o other.o print.o file.o -o outfile
add.o:add.c
	cc -c add.c
main.o:main.c
	cc -c main.c
delete.o:delete.c
	cc -c delete.c
other.o:other.c
	cc -c other.c
print.o:print.c
	cc -c print.c
file.o:file.c
	cc -c file.c 
clear:
	@echo "fenil savaliya"
	rm -v *.o
